version: '3.8'

services:
  afropedia-api:
    build: .
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/afropedia.log
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./ssl:/app/ssl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/ssl:ro
  #   depends_on:
  #     - afropedia-api
  #   restart: unless-stopped
