#!/bin/bash

echo "🔧 Afropedia FREE Environment Setup"
echo "=================================="

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}This script will help you set up environment variables for FREE deployment.${NC}"
echo -e "${YELLOW}You'll need your Supabase URL and key.${NC}\n"

# Get Supabase details
read -p "Enter your Supabase URL: " SUPABASE_URL
read -p "Enter your Supabase Key: " SUPABASE_KEY

# Generate JWT secret
echo -e "\n${YELLOW}Generating JWT secret...${NC}"
JWT_SECRET=$(openssl rand -base64 32)
echo -e "${GREEN}✅ JWT secret generated${NC}"

# Create Railway environment variables script
cat > set-railway-free-env.sh << EOF
#!/bin/bash
# Railway FREE Environment Variables Setup
echo "Setting Railway environment variables for FREE deployment..."

railway variables set SUPABASE_URL="$SUPABASE_URL"
railway variables set SUPABASE_KEY="$SUPABASE_KEY"
railway variables set JWT_SECRET="$JWT_SECRET"
railway variables set ENVIRONMENT="production"
railway variables set LOG_LEVEL="INFO"
railway variables set LOG_FILE="logs/afropedia.log"
railway variables set LOG_FORMAT="json"
railway variables set SSL_ENABLED="false"
railway variables set HTTPS_REDIRECT_ENABLED="false"
railway variables set SECURITY_HEADERS_ENABLED="true"
railway variables set MEILISEARCH_URL="http://localhost:7700"
railway variables set MEILISEARCH_MASTER_KEY="masterKey"

echo "✅ All Railway environment variables set for FREE deployment!"
EOF

chmod +x set-railway-free-env.sh

# Create local .env file for development
cat > wikipedia-clone-py-backend/.env << EOF
# Afropedia FREE Environment Configuration
# Generated by setup script

SUPABASE_URL=$SUPABASE_URL
SUPABASE_KEY=$SUPABASE_KEY
JWT_SECRET=$JWT_SECRET

# Production Environment Settings
ENVIRONMENT=production
LOG_LEVEL=INFO
LOG_FILE=logs/afropedia.log
LOG_FORMAT=json

# SSL Configuration (disabled for free tier)
SSL_ENABLED=false
SSL_CERT_FILE=ssl_config/certs/localhost.crt
SSL_KEY_FILE=ssl_config/certs/localhost.key
SSL_PORT=8443

# Security Settings
HTTPS_REDIRECT_ENABLED=false
SECURITY_HEADERS_ENABLED=true

# MeiliSearch Configuration (optional for free tier)
MEILISEARCH_URL=http://localhost:7700
MEILISEARCH_MASTER_KEY=masterKey

# CORS Configuration for FREE deployment
ALLOWED_ORIGINS=http://localhost:3000,https://afropedia-frontend.vercel.app
EOF

echo -e "\n${GREEN}✅ Environment setup complete!${NC}"
echo -e "\n${YELLOW}Next steps:${NC}"
echo "1. Run: ./set-railway-free-env.sh (to set Railway variables)"
echo "2. Run: ./deploy-free.sh (to deploy everything)"
echo "3. Your app will be live for FREE!"
echo ""
echo -e "${GREEN}💰 Total cost: $0/month${NC}"
